--- #YAML:1.0
name:               Net-LDAP-Class
version:            0.16
abstract:           object-relational mapper for Net::LDAP
author:
    - Peter Karman <karman@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Clone:                0
    Data::Dump:           0
    Digest::SHA1:         0
    MIME::Base64:         0
    Net::LDAP:            0
    Net::LDAP::Batch:     0
    Net::LDAP::Server::Test:  0.07
    Rose::Object:         0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
