--- #YAML:1.0
name:                Net-LDAP-Class
version:             0.12
abstract:            object-relational mapper for Net::LDAP
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Clone:                         0
    Data::Dump:                    0
    Digest::SHA1:                  0
    MIME::Base64:                  0
    Net::LDAP:                     0
    Net::LDAP::Batch:              0
    Net::LDAP::Server::Test:       0.07
    Rose::Object:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
